// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABaGJz0tDMehzo4n3-1SI8x_1KLzxFbak',
    appId: '1:177532129172:web:21ebf6f5247b20d8344981',
    messagingSenderId: '177532129172',
    projectId: 'to-do-98cf6',
    authDomain: 'to-do-98cf6.firebaseapp.com',
    storageBucket: 'to-do-98cf6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDKLSPzlx525DjqI99SeG5WgDdN7b7AE',
    appId: '1:177532129172:android:7d6cbf6ca4541d7e344981',
    messagingSenderId: '177532129172',
    projectId: 'to-do-98cf6',
    storageBucket: 'to-do-98cf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBYfy7poV8a5_yyna-x2BUJHHvFvt5UQ',
    appId: '1:177532129172:ios:c70351f3f889f098344981',
    messagingSenderId: '177532129172',
    projectId: 'to-do-98cf6',
    storageBucket: 'to-do-98cf6.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBYfy7poV8a5_yyna-x2BUJHHvFvt5UQ',
    appId: '1:177532129172:ios:c70351f3f889f098344981',
    messagingSenderId: '177532129172',
    projectId: 'to-do-98cf6',
    storageBucket: 'to-do-98cf6.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABaGJz0tDMehzo4n3-1SI8x_1KLzxFbak',
    appId: '1:177532129172:web:0705690d5fa34345344981',
    messagingSenderId: '177532129172',
    projectId: 'to-do-98cf6',
    authDomain: 'to-do-98cf6.firebaseapp.com',
    storageBucket: 'to-do-98cf6.appspot.com',
  );
}
